// <auto-generated />
namespace _02_agro.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class FixFarmContextSchema : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FixFarmContextSchema));
        
        string IMigrationMetadata.Id
        {
            get { return "202601212127339_FixFarmContextSchema"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
