// <auto-generated />
namespace _02_agro.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class Transactions : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Transactions));
        
        string IMigrationMetadata.Id
        {
            get { return "202601221747018_Transactions"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
